name: CI/CD

on:
  issues:
    types:
      - opened

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1
            - name: Build
              run: |
                  npm install
                  npm install -g firebase-tools
                  npm run build
            - name: Firebase Deploy
              env: 
                FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
              run: firebase deploy -P ${{ secrets.NEXT_PUBLIC_FIRE_APP_ID }}
