name: CI/CD

on:
  push:
    branches:
      - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1
            - name: Build
              run: |
                  npm install
                  npm install -g firebase-tools
                  npm run build
            - name: Firebase Deploy
              env: 
                FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
              run: |
                firebase experiments:enable webframeworks
                firebase use spoon-a7088
                firebase deploy
