name: CI/CD

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1
            - name: Build
              run: |
                  npm install
                  npm install -g firebase-tools
                  npm run build
            - name: Firebase Deploy
              env:
                  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
                  NEXT_PUBLIC_FIRE_API: ${{ secrets.NEXT_PUBLIC_FIRE_API }}
                  NEXT_PUBLIC_FIRE_APP_ID: ${{ secrets.NEXT_PUBLIC_FIRE_APP_ID }}
                  NEXT_PUBLIC_FIRE_AUTH_DOMAIN: ${{ secrets.NEXT_PUBLIC_FIRE_AUTH_DOMAIN }}
                  NEXT_PUBLIC_FIRE_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_FIRE_PROJECT_ID }}
                  NEXT_PUBLIC_IRE_BUCKET: ${{ secrets.NEXT_PUBLIC_IRE_BUCKET }}
                  NEXT_PUBLIC_FIRE_MESSAGE_ID: ${{ secrets.NEXT_PUBLIC_FIRE_MESSAGE_ID }}
              run: |
                  firebase experiments:enable webframeworks
                  firebase use spoon-a7088
                  firebase deploy
