name: build

on:
  pull_request:

jobs:
  release-pr:
    name: Publish PR
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - name: Build
        run: |
            npm install
            npm install -g firebase-tools
            npm run build
